export const env = {
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPEN_ROUTER_API_KEY: process.env.OPEN_ROUTER_API_KEY,
  GOOGLE_GENERATIVE_AI_API_KEY: process.env.GOOGLE_GENERATIVE_AI_API_KEY,
  OLLAMA_API_BASE_URL: process.env.OLLAMA_API_BASE_URL,
  XAI_API_KEY: process.env.XAI_API_KEY,
  TOGETHER_API_KEY: process.env.TOGETHER_API_KEY,
  TOGETHER_API_BASE_URL: process.env.TOGETHER_API_BASE_URL,
  AWS_BEDROCK_CONFIG: process.env.AWS_BEDROCK_CONFIG,
};
